apiVersion: v1
kind: Secret
metadata:
  name: lms-secrets
  namespace: lead-management
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: sa
  MONGO_INITDB_ROOT_PASSWORD: "p@ssw0rd"
  MongoDb__ConnectionString: "mongodb://sa:p%40ssw0rd@mongodb-service:27017/?authSource=admin"
  Jwt__Secret: "YourSuperSecretKeyThatIsAtLeast32CharactersLong!"
